LGMOD_S7: no delay if no RELEASE; kbd_mode removed (TODO: in hotplug only if keyboard); edit directfbrc before stagecraft; adjust mount wait

diff --git a/rootfs-common/etc/init.d/rcS-crashdog b/rootfs-common/etc/init.d/rcS-crashdog
--- a/rootfs-common/etc/init.d/rcS-crashdog
+++ b/rootfs-common/etc/init.d/rcS-crashdog
@@ -42,13 +42,20 @@ elif [ "$ACT" = check ]; then
 
 	for idx in 3 2 1; do
 		[ -f $CRASHCNT.$idx ] && continue
+		return 0; exit 0
+	done
+	{ rm -f $CRASHCNT.1; sync; } > /dev/kmsg 2>&1; # minus 1
+	echo 'rcS-crashdog: Error: crash limit MAX' > /dev/kmsg
+	return 1; exit 1; # something wrong: don't mount cramfs, don't start RELEASE
+
+elif [ "$ACT" = start ]; then
+	[ -f $CRASHON ] || { return 0; exit 0; }
+	for idx in 3 2 1; do
+		[ -f $CRASHCNT.$idx ] && continue
 		{ echo "rcS-crashdog: Crash limit $idx/3"
 			touch $CRASHCNT.$idx; sync; } > /dev/kmsg 2>&1
 		setsid sh /etc/init.d/rcS-crashdog watch &
 		return 0; exit 0
 	done
 
-	{ rm -f $CRASHCNT.1; sync; } > /dev/kmsg 2>&1; # minus 1
-	echo 'rcS-crashdog: Error: crash limit MAX' > /dev/kmsg
-	return 1; exit 1; # something wrong: don't mount cramfs, don't start RELEASE
 fi
