LGMOD_S7: fix for S6: dropbear, profile, /lib readwrite, /lib/ld-uClibc sym.link; fix extroot, usercall wait; few minor things

diff --git a/rootfs-common/etc/init.d/rcS-devrw b/rootfs-common/etc/init.d/rcS-devrw
--- a/rootfs-common/etc/init.d/rcS-devrw
+++ b/rootfs-common/etc/init.d/rcS-devrw
@@ -4,23 +4,36 @@
 
 SRC=/tmp/lgmod/Root; TFS=/tmp/lgmod/tmpfs
 
-d=/dev
-if ! touch $d/test-rw > /dev/null 2>&1; then
-	mkdir -p "$TFS$d"
+dorw() {
+	touch $1/test-rw > /dev/null 2>&1 && return 0
+	local d=$1 e; [ -d "$TFS$d" ] || mkdir -p "$TFS$d"
 
 	[ -d /sys/module/mini_fo ] ||
 		insmod /lib/modules/2.6.26/mini_fo.ko
 	[ -d /sys/module/mini_fo ] &&
-		mount -t mini_fo -o base="$d",sto="$TFS$d" "mini$d" "$d" &&
-		{ return 0; exit 0; }
+		mount -t mini_fo -o base="$d",sto="$TFS$d" "mini$d" "$d" && return 0
 
-	mkdir -p $SRC &&
-		mount -o bind / $SRC &&
-		cp "$SRC$d" "$TFS$d/../" && mount -o bind "$TFS$d" "$d" &&
-		{ return 0; exit 0; }
+	e=1; [ ! -d $SRC ] && mkdir -p $SRC && mount -o bind / $SRC
+	if [ "$d" = /dev ]; then cp -r "$SRC$d" "$TFS/" || e=2
+	elif [ "$d" = /lib ]; then for i in "$d/"*; do
+		if [ -h "$i" ]; then cp -a "$SRC$i" "$TFS$d/" || e=2
+		else ln -s "$SRC$i" "$TFS$d/" || e=2; fi; done
+	else e=3; fi
+	[ $e = 1 ] && mount -o bind "$TFS$d" "$d" && return 0
 
-	echo 'rcS-devrw: Error: /dev is not readwrite'
-	return 1; exit 1
+	echo "rcS-devrw: Error($e): $1 is not readwrite"
+	return $e
+}
+
+
+e=0
+
+dorw /dev || e=$?
+
+if [ ! -d /mnt/lg/lginit ]; then # S6
+	dorw /lib || e=$?
+	f=/mnt/lg/lgapp/lib/ld-uClibc.so.0
+	[ $e = 0 ] && [ -f $f ] && { ln -s $f /lib/ || e=10; }
 fi
 
-return 0; exit 0
+return $e; exit $e
diff --git a/rootfs-common/etc/init.d/rcS-services b/rootfs-common/etc/init.d/rcS-services
--- a/rootfs-common/etc/init.d/rcS-services
+++ b/rootfs-common/etc/init.d/rcS-services
@@ -24,35 +24,31 @@ fi
 # find extroot device and mount ext2/3 partition
 EXTLINK=/mnt/lg/user/extroot; EXTCONF=/mnt/lg/user/lgmod/extroot
 EXTMNT=/tmp/lgmod/extroot; EXTDEV=''; EXTYPE=''
-
+{
 if [ ! -f $EXTCONF ]; then
-	echo "rcS-services: Warning: not found: $EXTCONF" > /dev/kmsg
+	echo "rcS-services: Warning: not found: $EXTCONF"
 elif [ ! -h $EXTLINK ]; then
-	echo "rcS-services: Warning: not a sym.link: $EXTLINK" > /dev/kmsg
+	echo "rcS-services: Warning: not a sym.link: $EXTLINK"
 else
 	ID=`cat $EXTCONF`; EXTYPE="${ID%%:*}"; EXTDEV="${ID#*:}"; EXTDEV="${EXTDEV%%:*}"
-	[ "$EXTYPE" = ext3 ] && modprobe jbd
-	modprobe "$EXTYPE" && mkdir -p $EXTMNT || { EXTYPE=''; EXTDEV=''; }
-	[ -n "$EXTDEV" ] && [ -n "$EXTYPE" ] ||
-		echo "rcS-services: Error: invalid config: $EXTCONF" > /dev/kmsg
+	[ "$EXTYPE" = ext3 ] && [ ! -d /sys/module/jbd ] && insmod /lib/modules/2.6.26/jbd.ko
+	[ -d "/sys/module/$EXTYPE" ] || insmod "/lib/modules/2.6.26/$EXTYPE.ko"
+	[ -d "/sys/module/$EXTYPE" ] && mkdir -p $EXTMNT || { EXTYPE=''; EXTDEV=''; }
+	[ -n "$EXTDEV" ] && [ -n "$EXTYPE" ] || echo "rcS-services: Error: invalid config: $EXTCONF"
 fi
-
-[ -n "$EXTDEV" ] && [ -n "$EXTYPE" ] && {
+if [ -n "$EXTDEV" ] && [ -n "$EXTYPE" ]; then
 	for i in /sys/block/sd?; do
 		dev=${i##*/}; [ -d $i ] && [ -d "$i/$dev$EXTDEV" ] || continue
-		id="`cat $i/device/vendor`"; id="`echo $id`"
-		id="$id:`cat $i/device/../../../../serial`"
-		id="$id:`cat $i/device/../../../../idVendor`"
-		id="$id:`cat $i/device/../../../../idProduct`"
-		[ "$ID" = "$EXTYPE:$EXTDEV:$id" ] || continue; dev="/dev/$dev$EXTDEV"
-
-		mount -o noatime -t "$EXTYPE" "$dev" $EXTMNT ||
-			echo "rcS-services: Error: extroot mount -t $EXTYPE $dev"
-		break
+		id="`cat $i/device/vendor`"; id="`echo $id`";  id="$id:`cat $i/device/../../../../serial`"
+		id="$id:`cat $i/device/../../../../idVendor`"; id="$id:`cat $i/device/../../../../idProduct`"
+		[ "$ID" = "$EXTYPE:$EXTDEV:$id" ] && break
 	done
-	[ "$ID" = "$EXTYPE:$EXTDEV:$id" ] ||
-		echo "rcS-services: Error: extroot device not found: $ID"
-	} > /dev/kmsg 2>&1
+	if [ "$ID" = "$EXTYPE:$EXTDEV:$id" ]; then
+		mount -o noatime -t "$EXTYPE" "$/dev/$dev$EXTDEV" $EXTMNT ||
+			echo "rcS-services: Error: extroot mount -t $EXTYPE $/dev/$dev$EXTDEV"
+	else echo "rcS-services: Error: extroot device not found: $ID"; fi
+fi
+} > /dev/kmsg 2>&1
 
 . /etc/init.d/rcS-services-env
 
