LGMOD_S7 version: 1.0.10 alpha 5 - OPENRELEASE telnet, init options in Tools page

diff --git a/rootfs/etc/init.d/rcS-crashdog b/rootfs/etc/init.d/rcS-crashdog
--- a/rootfs/etc/init.d/rcS-crashdog
+++ b/rootfs/etc/init.d/rcS-crashdog
@@ -2,64 +2,53 @@
 # Source code released under GPL License
 # rcS for Saturn7 by mmm4m5m
 
-# Description: mark before mount cramfs and 'watch' (wait) for RELEASE - will it start or crash
+# Description: mark before mount cramfs, 'watch' (wait) for RELEASE, clear mark if no crash
 
-ACT="$1"; RCS_CRASHDOG="$2"
-[ "$RCS_CRASHDOG" = 0 ] && { return 0; exit 0; }
-
-LGMOD_CFG=/mnt/lg/user/lgmod
 CRASHON=/mnt/lg/cmn_data/crash-on
 CRASHCNT=/mnt/lg/cmn_data/crash-index
-CRASHCMD='sh /etc/init.d/rcS-crashdog check'
-RBIN=/mnt/lg/lgapp/RELEASE
-
-if [ "$ACT" = watch ] && [ ! -f $CRASHON ]; then
-	# TODO: more reasons to turn it ON - if nvram crc is wrong (xeros)
-	{ if [ -n "$RCS_CRASHDOG" ]; then
-		echo 'rcS-crashdog: ON (config)'; touch $CRASHON; sync
-	elif [ ! -d "$LGMOD_CFG" ]; then
-		echo 'rcS-crashdog: ON (lgmod)'; touch $CRASHON; sync
-	fi; } > /dev/kmsg 2>&1
-fi
-
+ACT="$1"; CRASHDOG="$2"
 
 if [ "$ACT" = error ]; then
-	echo 'rcS-chashdog: ON (error)' > /dev/kmsg
-	{ touch $CRASHON; sync; } > /dev/kmsg 2>&1
+	{ echo 'rcS-chashdog: ON (error)'; touch $CRASHON; sync; } > /dev/kmsg 2>&1
 
 elif [ "$ACT" = watch ]; then
-	[ -f $CRASHON ] || { return 0; exit 0; }
-	for idx in 3 2 1; do
-		if [ ! -f $CRASHCNT.$idx ]; then
-			echo "rcS-crashdog: Crash limit $idx/3" > /dev/kmsg
-			{ touch $CRASHCNT.$idx; sync; } > /dev/kmsg 2>&1
-			$CRASHCMD &
-			return 0; exit 0
-		fi
-	done
-	{ rm -f $CRASHCNT.1; sync; } > /dev/kmsg 2>&1; # minus 1
-	echo 'rcS-crashdog: Error: maximum crash limit reached' > /dev/kmsg
-	return 1; exit 1; # something wrong: don't mount cramfs, don't start RELEASE
-
-elif [ "$ACT" = check ]; then
 	{
-	sleep 25; # to manually trigger 'max crash limit' - fast power off TV
-	for i in 1 2 3 4 5 6 7; do
-		if pgrep -f "^$RBIN" > /dev/null; then
+	sleep 20; # to manually trigger 'crash limit MAX' - fast power off TV
+	for i in 1 2 3 4 5 6 7 8; do
+		sleep 5; r=$(pgrep -f '^/mnt/lg/lgapp/RELEASE' | wc -l)
+		[ "$r" -lt 2 ] || {
 			if [ -f $CRASHCNT.1 ]; then
-				echo 'rcS-crashdog: crash count=0'
-				rm -f $CRASHCNT.*; sync
+				echo 'rcS-crashdog: crash count=0'; rm -f $CRASHCNT.*; sync
 			else
-				echo 'rcS-crashdog: OFF'
-				rm -f $CRASHCNT.* $CRASHON; sync
+				echo 'rcS-crashdog: OFF'; rm -f $CRASHCNT.* $CRASHON; sync
 			fi
-			return 0; exit 0
-		fi
-		sleep 5
+			return 0; exit 0; }
 	done
 	echo 'rcS-crashdog: Warning: crash count+1'
 	} > /dev/kmsg 2>&1
 
-fi
+elif [ "$ACT" = check ]; then
+	if [ ! -f $CRASHON ]; then
+		# TODO: more reasons to turn it ON - if nvram crc is wrong (xeros)
+		{
+		if [ -n "$CRASHDOG" ]; then
+			echo 'rcS-crashdog: ON (config)'; touch $CRASHON; sync
+		elif [ ! -d /mnt/lg/user/lgmod ]; then
+			echo 'rcS-crashdog: ON (lgmod)'; touch $CRASHON; sync
+		fi
+		} > /dev/kmsg 2>&1
+	fi
+	[ -f $CRASHON ] || { return 0; exit 0; }
 
-return 1; exit 1
+	for idx in 3 2 1; do
+		[ -f $CRASHCNT.$idx ] && continue
+		{ echo "rcS-crashdog: Crash limit $idx/3"
+			touch $CRASHCNT.$idx; sync; } > /dev/kmsg 2>&1
+		sh /etc/init.d/rcS-crashdog watch &
+		return 0; exit 0
+	done
+
+	{ rm -f $CRASHCNT.1; sync; } > /dev/kmsg 2>&1; # minus 1
+	echo 'rcS-crashdog: Error: crash limit MAX' > /dev/kmsg
+	return 1; exit 1; # something wrong: don't mount cramfs, don't start RELEASE
+fi
diff --git a/rootfs/etc/init.d/rcS-devrw b/rootfs/etc/init.d/rcS-devrw
--- a/rootfs/etc/init.d/rcS-devrw
+++ b/rootfs/etc/init.d/rcS-devrw
@@ -6,17 +6,18 @@ SRC=/tmp/lgmod/Root; TFS=/tmp/lgmod/tmpfs
 
 d=/dev
 if ! touch $d/test-rw > /dev/null 2>&1; then
-	insmod /lib/modules/mini_fo.ko > /dev/null 2>&1
+	mkdir -p "$TFS$d"
 
-	mkdir -p "$TFS$d" &&
-		mount -t mini_fo -o base="$d",sto="$TFS$d" "mini$d" "$d" &&
+	modprobe /lib/modules/mini_fo.ko > /dev/null 2>&1
+	mount -t mini_fo -o base="$d",sto="$TFS$d" "mini$d" "$d" &&
 		{ return 0; exit 0; }
 
-	mkdir -p $SRC &&
-		mount -o bind / $SRC &&
-		cp "$SRC$d" "$TFS$d/../" &&
-		mount -o bind "$TFS$d" "$d" ||
-		{ echo 'rcS-devrw: Error: /dev is not readwrite'; return 1; exit 1; }
+	mkdir -p $SRC; mount -o bind / $SRC &&
+	cp "$SRC$d" "$TFS$d/../" && mount -o bind "$TFS$d" "$d" &&
+		{ return 0; exit 0; }
+
+	echo 'rcS-devrw: Error: /dev is not readwrite'
+	return 1; exit 1
 fi
 
 return 0; exit 0
diff --git a/rootfs/etc/init.d/rcS-exec b/rootfs/etc/init.d/rcS-exec
--- a/rootfs/etc/init.d/rcS-exec
+++ b/rootfs/etc/init.d/rcS-exec
@@ -3,73 +3,54 @@
 # OpenLGTV BCM by xeros
 # Modified for Saturn7 by mmm4m5m
 
-# accepted config values: empty or non-empty
+# [chroot] [overlay]
+# config values: empty or non-empty
+RCS_SYSLOG=1; # 1=enable
 RCS_NOREL=''
-RCS_CRAMFS=1
-RCS_DELAY=15
-#RCS_RELEASE=OPENREL-TMUX-PIPE
-#RCS_RELEASE=OPENREL-TMUX
-#RCS_RELEASE=OPENRELEASE
-RCS_RELEASE=OPENREL-DAEMON; # in bg
-#RCS_RELEASE=TMUX-PIPE
-#RCS_RELEASE=TMUX; # insmod pty.ko; in bg
-#RCS_RELEASE=''; # LG
+RCS_NOREL_ONCE=''
+RCS_DELAY=15; # seconds delay before services
 RCS_CRASHDOG=''; # ''=default; 0=disable; 1=enable/enforce
-RUN=/mnt/lg/user/lgmod/init/rcS
-CFG=/mnt/lg/user/lgmod
+RUN=/mnt/lg/user/lgmod/init/rcS; BOOTMOD=/mnt/lg/user/lgmod/boot
 
+export HOME=/mnt/lg/user/root
+. /etc/init.d/rcS-lginit-env; # LG: env
 
 . /etc/init.d/rcS-tmpfs
 
-{ syslogd -C16; mkdir -p /tmp/var/log /tmp/var/run/tmux; f='/var/run/utmp /var/log/wtmp'
-touch $f /var/log/lastlog; chgrp utmp $f; chmod 0664 $f; } > /dev/kmsg 2>&1
-
-# environment - minimal
-export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
-export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
-export TERM=vt100
-export HOME=/mnt/lg/user/root
-
-[ -f $CFG/tvstartup ] || RCS_RELEASE=''; # LG
-
-# lgmod: rc.sysinit rc.local
-[ -e $CFG/debug ] && { RCS_NOREL=1; echo 'LGMOD: DEBUG!'; rm -f $CFG/debug; sync; } >/dev/kmsg 2>&1
-
-[ -f "$RUN" ] && { echo "rcS: Found $RUN" > /dev/kmsg; . "$RUN"; }
+{ mkdir -p /tmp/var/log /tmp/var/run/tmux; f='/var/run/utmp /var/log/wtmp'
+	touch /var/log/lastlog $f; chgrp utmp $f; chmod 0664 $f; } > /dev/kmsg 2>&1
 
 
-#CHR=/tmp/lgmod/Overlay; CHRO=/tmp/lgmod/overlay; # lginit
-#OVERLAY=''; [ -d "$CHR" ] && [ $(stat -c%D / /tmp "$CHR"|sort|uniq|wc -l) = 3 ] && OVERLAY=yes
-#[ -z "$OVERLAY" ] && [ -d "$CHRO" ] && [ $(stat -c%D / /tmp "$CHRO"|sort|uniq|wc -l) = 3 ] && OVERLAY=yes
-touch /test-rw > /dev/null 2>&1 && OVERLAY=1 || OVERLAY=''
-
-. /etc/init.d/rcS-lginit-env; # LG: env
-[ -f "$RUN-init" ] && { echo "rcS-exec: Found $RUN-init" > /dev/kmsg; . "$RUN-init"; }
-. /etc/init.d/rcS-lginit "$OVERLAY"; # LG: mount
-[ -f "$RUN-mount" ] && { echo "rcS-exec: Found $RUN-mount" > /dev/kmsg; . "$RUN-mount"; }
-
-
-. /etc/init.d/rcS-nvram
-
-if [ -z "$RCS_NOREL" ]; then
-	. /etc/init.d/rcS-crashdog watch "$RCS_CRASHDOG" ||
-		{ RCS_NOREL=1; . /etc/init.d/rcS-crashdog minus1 "$RCS_CRASHDOG"; }
+if [ -f "$BOOTMOD" ]; then
+	echo "rcS: Found $BOOTMOD" > /dev/kmsg; . "$BOOTMOD"
+	[ -n "$RCS_NOREL_ONCE" ] && { RCS_NOREL="$RCS_NOREL_ONCE"; sed -ie '/^RCS_NOREL_ONCE=/d' "$BOOTMOD" > /dev/kmsg 2>&1; }
+	[ -n "$RCS_NOREL_ONCE" ] && sync > /dev/kmsg 2>&1
 fi
 
+[ "$RCS_SYSLOG" = 1 ] && syslogd -C16 > /dev/kmsg 2>&1
+
+[ -f "$RUN-init" ] && { echo "rcS-exec: Found $RUN-init" > /dev/kmsg; . "$RUN-init"; }
+. /etc/init.d/rcS-lginit; # LG: mount
+[ -f "$RUN-mount" ] && { echo "rcS-exec: Found $RUN-mount" > /dev/kmsg; . "$RUN-mount"; }
+
+. /etc/init.d/rcS-nvram
+setsid sh /etc/init.d/rcS-services "$RCS_DELAY" &
+
+
+[ -n "$RCS_BREAK_CTRL_C" ] && { echo 'Note: Press "exit" to continue...'; sh; }
+
+if [ -z "$RCS_NOREL" ] && [ "$RCS_CRASHDOG" != 0 ]; then
+	. /etc/init.d/rcS-crashdog check "$RCS_CRASHDOG" || RCS_NOREL=1; fi
 
 if [ -z "$RCS_NOREL" ]; then
-	Rbg=''; . /etc/init.d/rcS-release bg "$RCS_RELEASE" && Rbg=1; # Rtm
-	sh /etc/init.d/rcS-services "$RCS_NOREL" "$Rbg" "$RCS_DELAY" &
-	. /etc/init.d/release boot "$RCS_RELEASE" "$RCS_CRAMFS" "$Rtm"
-	if [ -z "$Rbg" ]; then
-		echo "rcS-exec: Error $?" > /dev/kmsg
-		. /etc/init.d/rcS-crashdog error "$RCS_CRASHDOG"
-		echo 'rcS: help - sh  : $ call debug_os_shell+0xb0' > /dev/kmsg
-		echo 'rcS: help - user: # cd / && tar xzvf /mnt/usb1/Drive1/backup-user.tar.gz' > /dev/kmsg
-		exec sh; exit 1
-	fi
-else
-	. /etc/init.d/rcS-services "$RCS_NOREL" 0 0
+	err=''; . /etc/init.d/release boot || err=$?
+	if [ -z "$err" ]; then
+		sleep 5; r=$(pgrep -f '^/mnt/lg/lgapp/RELEASE' | wc -l)
+		[ "$r" -lt 2 ] && err=1; fi
+	[ -n "$err" ] && {
+		echo "rcS-release: Error $err ($Mode)" > /dev/kmsg
+		. /etc/init.d/rcS-crashdog error
+		exec sh; exit 1; }
 fi
 
 exit 0
